{
 "title": "Cluster Information",
 "tags": [
  "jupyterhub",
  "kubernetes"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "cluster", "label": "cluster" },
   { "name": "PROMETHEUS_DS", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Cluster Utilization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Running Users",
   "type": "timeseries",
   "description": "Number of currently running users per hub.\n\nCommon shapes this visualization may take:\n1. A large number of users starting servers at exactly the same time will be\n  visible here as a single spike, and may cause stability issues. Since\n  they share the same cluster, such spikes happening on a *different* hub\n  may still affect your hub.\n",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "# Sum up all running user pods by namespace\nsum(\n  # Grab a list of all running pods.\n  # The group aggregator always returns \"1\" for the number of times each\n  # unique label appears in the time series. This is desirable for this\n  # use case because we're merely identifying running pods by name,\n  # not how many times they might be running.\n  group(\n    kube_pod_status_phase{phase=\"Running\"}\n  ) by (pod)\n  * on (pod) group_right() group(\n    kube_pod_labels{label_app=\"jupyterhub\", label_component=\"singleuser-server\"}\n  ) by (namespace, pod)\n) by (namespace)\n",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Node Count",
   "type": "timeseries",
   "description": "Number of nodes in each nodepool in this cluster\n",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "# sum up all nodes by nodepool\nsum(\n  # kube_pod_labels comes from\n  # https://github.com/kubernetes/kube-state-metrics, and there is a particular\n  # label (kubernetes_node) that lists the node on which the kube-state-metrics pod\n  # s running! So that's totally irrelevant to these queries, but when a nodepool\n  # is rotated it caused there to exist two metrics with the same node value (which\n  # we care about) but different kubernetes_node values (because kube-state-metrics\n  # was running in a different node, even though we don't care about that). This\n  # group really just drops all labels except the two we care about to\n  # avoid messing things up.\n  group(\n    kube_node_labels\n  ) by (node, label_alpha_eksctl_io_nodegroup_name, label_cloud_google_com_gke_nodepool, label_kubernetes_azure_com_agentpool)\n) by (label_alpha_eksctl_io_nodegroup_name, label_cloud_google_com_gke_nodepool, label_kubernetes_azure_com_agentpool)\n",
     "legendFormat": "{{label_alpha_eksctl_io_nodegroup_name}}{{label_cloud_google_com_gke_nodepool}}{{label_kubernetes_azure_com_agentpool}}"
    }
   ]
  },
  { "title": "Cluster Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Non Running Pods",
   "type": "timeseries",
   "description": "Pods in a non-running state in the hub's namespace.\n\nPods stuck in non-running states often indicate an error condition\n",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "sum(\n  kube_pod_status_phase{phase!=\"Running\"}\n) by (phase)\n",
     "legendFormat": "{{phase}}"
    }
   ]
  },
  {
   "title": "Pod terminations",
   "type": "table",
   "description": "This panel tracks pod terminations, for example, a pod being evicted from\na node under memory pressure. A Pod can, however, be in a \"Failed\" or\n\"Completed\" state without being listed here, for instance, if one of its\ncontainers exits with or without an error code.\n\nA pod termination reason can be either Evicted, NodeAffinity, NodeLost,\nShutdown, or UnexpectedAdmissionError.\n\n[Node-pressure eviction] is the process by which the kubelet proactively\nterminates pods to reclaim resources on nodes, such as memory. If you\nobserve pod evictions, consider adjusting the pod's [resource requests and\nlimits]. If a JupyterHub-started user-server pod is evicted, the user must\nrestart it manually via JupyterHub, which is a poor user experience to\navoid.\n\nAs this panel detects changes in pods' reported \"status.reason\", it can\nfail to detect pod terminations if the Pod is deleted quickly after it is\nterminated.\n\n[node-pressure eviction]: https://kubernetes.io/docs/concepts/scheduling-eviction/node-pressure-eviction/\n[resource requests and limits]: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/\n",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": "count(\n  # kube_pod_status_reason's time series values can be either zero or\n  # one, but only when it is one do we have a pod termination reason to\n  # consider.\n  #\n  # ref: https://github.com/kubernetes/kube-state-metrics/blob/main/docs/metrics/workload/pod-metrics.md\n  #\n  kube_pod_status_reason == 1\n  unless\n  kube_pod_status_reason offset $__interval == 1\n) by (reason, namespace, pod)\n"
    }
   ]
  },
  {
   "title": "Processes terminated by the out-of-memory killer, per node",
   "type": "timeseries",
   "description": "When a Kubernetes Pod's container exceeds its memory limit, the Linux\noom-killer terminates one or more of the container's high-memory\nprocesses. If the container's main process (PID 1) is terminated, the\ncontainer typically restarts automatically, as it is the default behavior\nfor k8s Pods' containers.\n\nHowever, if a non-main process is terminated, the container continues to\nrun. For example, a Jupyter server running as PID 1 might spawn multiple\nJupyter kernel processes. If the OOM killer terminates one of these kernel\nprocesses (because it consumed the most memory), only that kernel dies—the\ncontainer itself does not restart.\n\n---\n\nAs a Kubernetes administrator, you could check logs on the Kubernetes node\nfor details about what specific process was killed. You can see the\ncommand (like python or node), but not the full command-line arguments.\n\n```shell\n# access node via a very privileged pod\nkubectl debug node/<node-name> -it --image=docker.io/library/ubuntu --profile=sysadmin -- chroot /host bash\n\n# inspect relevant logs\ndmesg -T\n```\n",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "(\n  # oom kills are distinct events, so we want to see how many happened\n  # rather an average, to accomplish this we must do this subtraction\n  (\n    node_vmstat_oom_kill\n    -\n    node_vmstat_oom_kill offset $__interval\n  )\n  * on(node) group_left(label_alpha_eksctl_io_nodegroup_name, label_cloud_google_com_gke_nodepool, label_kubernetes_azure_com_agentpool)\n  group(\n    kube_node_labels\n  ) by (node, label_alpha_eksctl_io_nodegroup_name, label_cloud_google_com_gke_nodepool, label_kubernetes_azure_com_agentpool)\n) > 0\n",
     "legendFormat": "{{label_alpha_eksctl_io_nodegroup_name}}{{label_cloud_google_com_gke_nodepool}}{{label_kubernetes_azure_com_agentpool}}/{{node}}"
    }
   ]
  },
  {
   "title": "Container terminations (only failures)",
   "type": "table",
   "description": "This panel tracks the (init-)container termination reasons: OOMKilled,\nError, and ContainerStatusUnknown, excluding Completed.\n\nNote that container terminations that coincide with pod deletions may not\nbe detected because, after the pod deletion, the container termination reason is no\nlonger available.\n",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 22 },
   "targets": [
    {
     "expr": "# container failures, reliably detected via restarts counter\nlabel_replace(\n  group(\n    kube_pod_container_status_restarts_total\n    -\n    (\n      kube_pod_container_status_restarts_total offset $__interval\n      or\n      kube_pod_container_status_restarts_total * 0\n    )\n    > 0\n  ) by (namespace, pod, container)\n  * on (namespace, pod, container) group_left(reason)\n  # topk ensures a single reason label if multiple were available during\n  # the time interval, while last_over_time helps us get the terminated\n  # reason more reliably\n  topk(1, last_over_time(kube_pod_container_status_last_terminated_reason{reason!=\"Completed\"}[$__interval])) by (namespace, pod, container),\n  \"restarted\", \"yes\", \"\", \"\"\n)\n"
    },
    {
     "expr": "# init-container failures, reliably detected via restarts counter\nlabel_replace(\n  group(\n    kube_pod_init_container_status_restarts_total\n    -\n    (\n      kube_pod_init_container_status_restarts_total offset $__interval\n      or\n      kube_pod_init_container_status_restarts_total * 0\n    )\n    > 0\n  ) by (namespace, pod, container)\n  * on (namespace, pod, container) group_left(reason)\n  # topk ensures a single reason label if multiple were available during\n  # the time interval, while last_over_time helps us get the terminated\n  # reason more reliably\n  topk(1, last_over_time(kube_pod_init_container_status_last_terminated_reason{reason!=\"Completed\"}[$__interval])) by (namespace, pod, container),\n  \"restarted\", \"yes\", \"\", \"\"\n)\n"
    },
    {
     "expr": "# remaining container terminations, not so reliably detected,\n# because pods can be removed shortly after a container termination,\n# and the termination reason needs to be scraped before that\nlabel_replace(\n  group(\n    kube_pod_container_status_terminated_reason{reason!=\"Completed\"} == 1\n    unless on (namespace, pod)\n    (\n      kube_pod_container_status_terminated_reason{reason!=\"Completed\"} offset $__interval == 1\n      or\n      kube_pod_container_status_restarts_total > 0\n    )\n  ) by (reason, namespace, pod, container),\n  \"restarted\", \"no\", \"\", \"\"\n)\n"
    },
    {
     "expr": "# remaining init-container terminations, not so reliably detected,\n# because pods can be removed shortly after a container termination,\n# and the termination reason needs to be scraped before that\nlabel_replace(\n  group(\n    kube_pod_init_container_status_terminated_reason{reason!=\"Completed\"} == 1\n    unless on (namespace, pod)\n    (\n      kube_pod_init_container_status_terminated_reason{reason!=\"Completed\"} offset $__interval == 1\n      or\n      kube_pod_init_container_status_restarts_total > 0\n    )\n  ) by (reason, namespace, pod, container),\n  \"restarted\", \"no\", \"\", \"\"\n)\n"
    }
   ]
  },
  { "title": "Node Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Node CPU Utilization %",
   "type": "timeseries",
   "description": "% of available CPU currently in use\n",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(\n  sum(rate(node_cpu_seconds_total{mode!=\"idle\"}[5m])) by (node)\n  /\n  sum(kube_node_status_capacity{resource=\"cpu\"}) by (node)\n) * on (node) group_left(label_alpha_eksctl_io_nodegroup_name, label_cloud_google_com_gke_nodepool, label_kubernetes_azure_com_agentpool)\ngroup(\n  kube_node_labels\n) by (node, label_alpha_eksctl_io_nodegroup_name, label_cloud_google_com_gke_nodepool, label_kubernetes_azure_com_agentpool)\n",
     "legendFormat": "{{label_alpha_eksctl_io_nodegroup_name}}{{label_cloud_google_com_gke_nodepool}}{{label_kubernetes_azure_com_agentpool}}/{{node}}"
    }
   ]
  },
  {
   "title": "Node Memory Utilization %",
   "type": "timeseries",
   "description": "% of available Memory currently in use\n",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1 - (\n  sum (\n    # Memory that can be allocated to processes when they need\n    node_memory_MemFree_bytes + # Unused bytes\n    node_memory_Cached_bytes + # Shared memory + temporary disk cache\n    node_memory_Buffers_bytes # Very temporary buffer memory cache for disk i/o\n  ) by (node)\n  /\n  sum(node_memory_MemTotal_bytes) by (node)\n) * on(node) group_left(label_alpha_eksctl_io_nodegroup_name, label_cloud_google_com_gke_nodepool, label_kubernetes_azure_com_agentpool)\ngroup(\n  kube_node_labels\n) by (node, label_alpha_eksctl_io_nodegroup_name, label_cloud_google_com_gke_nodepool, label_kubernetes_azure_com_agentpool)\n",
     "legendFormat": "{{label_alpha_eksctl_io_nodegroup_name}}{{label_cloud_google_com_gke_nodepool}}{{label_kubernetes_azure_com_agentpool}}/{{node}}"
    }
   ]
  },
  {
   "title": "Node CPU Commit %",
   "type": "timeseries",
   "description": "% of each node guaranteed to pods on it\n",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(\n  # Get individual container cpu requests\n  kube_pod_container_resource_requests{resource=\"cpu\"}\n  # Add node pool name as label\n  * on(node) group_left(label_alpha_eksctl_io_nodegroup_name, label_cloud_google_com_gke_nodepool, label_kubernetes_azure_com_agentpool)\n  # group aggregator ensures that node names are unique per\n  # pool.\n  group(\n    kube_node_labels\n  ) by (node, label_alpha_eksctl_io_nodegroup_name, label_cloud_google_com_gke_nodepool, label_kubernetes_azure_com_agentpool)\n  # Ignore containers from pods that aren't currently running or scheduled\n  # FIXME: This isn't the best metric here, evaluate what is.\n  and on (pod) kube_pod_status_scheduled{condition='true'}\n  # Ignore user and node placeholder pods\n  and on (pod) kube_pod_labels{label_component!~'user-placeholder|node-placeholder'}\n) by (node, label_alpha_eksctl_io_nodegroup_name, label_cloud_google_com_gke_nodepool, label_kubernetes_azure_com_agentpool)\n/\nsum(\n  # Total allocatable CPU on a node\n  kube_node_status_allocatable{resource=\"cpu\"}\n  # Add nodepool name as label\n  * on(node) group_left(label_alpha_eksctl_io_nodegroup_name, label_cloud_google_com_gke_nodepool, label_kubernetes_azure_com_agentpool)\n  # group aggregator ensures that node names are unique per\n  # pool.\n  group(\n    kube_node_labels\n  ) by (node, label_alpha_eksctl_io_nodegroup_name, label_cloud_google_com_gke_nodepool, label_kubernetes_azure_com_agentpool)\n) by (node, label_alpha_eksctl_io_nodegroup_name, label_cloud_google_com_gke_nodepool, label_kubernetes_azure_com_agentpool)\n",
     "legendFormat": "{{label_alpha_eksctl_io_nodegroup_name}}{{label_cloud_google_com_gke_nodepool}}{{label_kubernetes_azure_com_agentpool}}/{{node}}"
    }
   ]
  },
  {
   "title": "Node Memory Commit %",
   "type": "timeseries",
   "description": "% of each node guaranteed to pods on it.\n\nWhen this hits 100%, the autoscaler will spawn a new node and the scheduler will stop\nputting pods on the old node.\n",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(\n  # Get individual container memory requests\n  kube_pod_container_resource_requests{resource=\"memory\"}\n  # Add node pool name as label\n  * on(node) group_left(label_alpha_eksctl_io_nodegroup_name, label_cloud_google_com_gke_nodepool, label_kubernetes_azure_com_agentpool)\n  # group aggregator ensures that node names are unique per\n  # pool.\n  group(\n    kube_node_labels\n  ) by (node, label_alpha_eksctl_io_nodegroup_name, label_cloud_google_com_gke_nodepool, label_kubernetes_azure_com_agentpool)\n  # Ignore containers from pods that aren't currently running or scheduled\n  # FIXME: This isn't the best metric here, evaluate what is.\n  and on (pod) kube_pod_status_scheduled{condition='true'}\n  # Ignore user and node placeholder pods\n  and on (pod) kube_pod_labels{label_component!~'user-placeholder|node-placeholder'}\n) by (node, label_alpha_eksctl_io_nodegroup_name, label_cloud_google_com_gke_nodepool, label_kubernetes_azure_com_agentpool)\n/\nsum(\n  # Total allocatable memory on a node\n  kube_node_status_allocatable{resource=\"memory\"}\n  # Add nodepool name as label\n  * on(node) group_left(label_alpha_eksctl_io_nodegroup_name, label_cloud_google_com_gke_nodepool, label_kubernetes_azure_com_agentpool)\n  # group aggregator ensures that node names are unique per\n  # pool.\n  group(\n    kube_node_labels\n  ) by (node, label_alpha_eksctl_io_nodegroup_name, label_cloud_google_com_gke_nodepool, label_kubernetes_azure_com_agentpool)\n) by (node, label_alpha_eksctl_io_nodegroup_name, label_cloud_google_com_gke_nodepool, label_kubernetes_azure_com_agentpool)\n",
     "legendFormat": "{{label_alpha_eksctl_io_nodegroup_name}}{{label_cloud_google_com_gke_nodepool}}{{label_kubernetes_azure_com_agentpool}}/{{node}}"
    }
   ]
  },
  {
   "title": "Node Pool CPU commitment %",
   "type": "timeseries",
   "description": "% of CPU in each node pool guaranteed to user workloads.\n\nMost commonly, JupyterHub workloads are *memory bound*, not CPU bound. So this is\nnot a particularly helpful graph.\n\nCommon shapes this visualization may take:\n1. If this is *consistently high* but shaped differently than your memory commitment\n  graph, consider changing your CPU requirements.\n",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(\n  # Get individual container memory requests\n  kube_pod_container_resource_requests{resource=\"cpu\"}\n  # Add node pool name as label\n  * on(node) group_left(label_alpha_eksctl_io_nodegroup_name, label_cloud_google_com_gke_nodepool, label_kubernetes_azure_com_agentpool)\n  # group aggregator ensures that node names are unique per\n  # pool.\n  group(\n    kube_node_labels\n  ) by (node, label_alpha_eksctl_io_nodegroup_name, label_cloud_google_com_gke_nodepool, label_kubernetes_azure_com_agentpool)\n  # Ignore containers from pods that aren't currently running or scheduled\n  # FIXME: This isn't the best metric here, evaluate what is.\n  and on (pod) kube_pod_status_scheduled{condition='true'}\n  # Ignore user and node placeholder pods\n  and on (pod) kube_pod_labels{label_component!~'user-placeholder|node-placeholder'}\n) by (label_alpha_eksctl_io_nodegroup_name, label_cloud_google_com_gke_nodepool, label_kubernetes_azure_com_agentpool)\n/\nsum(\n  # Total allocatable CPU on a node\n  kube_node_status_allocatable{resource=\"cpu\"}\n  # Add nodepool name as label\n  * on(node) group_left(label_alpha_eksctl_io_nodegroup_name, label_cloud_google_com_gke_nodepool, label_kubernetes_azure_com_agentpool)\n  # group aggregator ensures that node names are unique per\n  # pool.\n  group(\n    kube_node_labels\n  ) by (node, label_alpha_eksctl_io_nodegroup_name, label_cloud_google_com_gke_nodepool, label_kubernetes_azure_com_agentpool)\n) by (label_alpha_eksctl_io_nodegroup_name, label_cloud_google_com_gke_nodepool, label_kubernetes_azure_com_agentpool)\n",
     "legendFormat": "{{label_alpha_eksctl_io_nodegroup_name}}{{label_cloud_google_com_gke_nodepool}}{{label_kubernetes_azure_com_agentpool}}"
    }
   ]
  },
  {
   "title": "Node Pool Memory commitment %",
   "type": "timeseries",
   "description": "% of memory in each node pool guaranteed to user workloads.\n\nCommon shapes this visualization may take:\n1. If this is consistently low (<50%), you are paying for cloud compute that you do not\n  need. Consider reducing the size of your nodes, or increasing the amount of\n  memory guaranteed to your users. Some variability based on time of day is to be expected.\n",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(\n  # Get individual container memory requests\n  kube_pod_container_resource_requests{resource=\"memory\"}\n  # Add node pool name as label\n  * on(node) group_left(label_alpha_eksctl_io_nodegroup_name, label_cloud_google_com_gke_nodepool, label_kubernetes_azure_com_agentpool)\n  # group aggregator ensures that node names are unique per\n  # pool.\n  group(\n    kube_node_labels\n  ) by (node, label_alpha_eksctl_io_nodegroup_name, label_cloud_google_com_gke_nodepool, label_kubernetes_azure_com_agentpool)\n  # Ignore containers from pods that aren't currently running or scheduled\n  # FIXME: This isn't the best metric here, evaluate what is.\n  and on (pod) kube_pod_status_scheduled{condition='true'}\n  # Ignore user and node placeholder pods\n  and on (pod) kube_pod_labels{label_component!~'user-placeholder|node-placeholder'}\n) by (label_alpha_eksctl_io_nodegroup_name, label_cloud_google_com_gke_nodepool, label_kubernetes_azure_com_agentpool)\n/\nsum(\n  # Total allocatable memory on a node\n  kube_node_status_allocatable{resource=\"memory\"}\n  # Add nodepool name as label\n  * on(node) group_left(label_alpha_eksctl_io_nodegroup_name, label_cloud_google_com_gke_nodepool, label_kubernetes_azure_com_agentpool)\n  # group aggregator ensures that node names are unique per\n  # pool.\n  group(\n    kube_node_labels\n  ) by (node, label_alpha_eksctl_io_nodegroup_name, label_cloud_google_com_gke_nodepool, label_kubernetes_azure_com_agentpool)\n) by (label_alpha_eksctl_io_nodegroup_name, label_cloud_google_com_gke_nodepool, label_kubernetes_azure_com_agentpool)\n",
     "legendFormat": "{{label_alpha_eksctl_io_nodegroup_name}}{{label_cloud_google_com_gke_nodepool}}{{label_kubernetes_azure_com_agentpool}}"
    }
   ]
  }
 ]
}