{
 "title": "JupyterHub Dashboard",
 "tags": [ "jupyterhub" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   {
    "name": "hub",
    "query": "label_values(kube_service_labels{service=\"hub\"}, namespace)"
   }
  ]
 },
 "panels": [
  { "title": "Container Images", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Images used by user pods",
   "type": "timeseries",
   "description": "Number of user servers using a container image.\n",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum (\n  # User pods are named \"notebook\" by kubespawner\n  kube_pod_container_info{container=\"notebook\", namespace=~\"$hub\"}\n) by (image_spec, namespace)\n",
     "legendFormat": "{{ namespace }}: {{ image_spec }}"
    }
   ]
  },
  {
   "title": "User Resource Utilization stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 }
  },
  {
   "title": "User active age distribution",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "time()\n-\n(\n  kube_pod_created\n  * on (namespace, pod)  \n  group(\n    kube_pod_labels{label_app=\"jupyterhub\", label_component=\"singleuser-server\", namespace=~\"$hub\"}\n  ) by (label_component, pod, namespace)\n)\n"
    }
   ]
  },
  {
   "title": "User CPU usage distribution",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": "sum(\n  # exclude name=\"\" because the same container can be reported\n  # with both no name and `name=k8s_...`,\n  # in which case sum() by (pod) reports double the actual metric\n  irate(container_cpu_usage_seconds_total{name!=\"\"}[5m])\n  * on (namespace, pod) group_left(container) \n  group(\n    kube_pod_labels{label_app=\"jupyterhub\", label_component=\"singleuser-server\", namespace=~\"$hub\"}\n  ) by (label_component, pod, namespace)\n) by (pod)\n"
    }
   ]
  },
  {
   "title": "User memory usage distribution",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "sum(\n  # exclude name=\"\" because the same container can be reported\n  # with both no name and `name=k8s_...`,\n  # in which case sum() by (pod) reports double the actual metric\n  container_memory_working_set_bytes{name!=\"\"}\n  * on (namespace, pod) group_left(container) \n  group(\n    kube_pod_labels{label_app=\"jupyterhub\", label_component=\"singleuser-server\", namespace=~\"$hub\"}\n  ) by (label_component, pod, namespace)\n) by (pod)\n"
    }
   ]
  },
  { "title": "Hub Diagnostics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Server Start Times",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "sum by (le) (\n  jupyterhub_server_spawn_duration_seconds_bucket{namespace=~\"$hub\"}\n  -\n  jupyterhub_server_spawn_duration_seconds_bucket{namespace=~\"$hub\"}\n  offset $__rate_interval\n)\n"
    }
   ]
  },
  {
   "title": "Server Start Failures",
   "type": "timeseries",
   "description": "Attempts by users to start servers that failed.\n",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 33 },
   "targets": [
    {
     "expr": "sum(increase(jupyterhub_server_spawn_duration_seconds_count{status!=\"success\", namespace=~\"$hub\"}[2m])) by (status)\n",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Hub response latency",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 43 },
   "targets": [
    {
     "expr": "# Ignore SpawnProgressAPIHandler, as it is a EventSource stream\n# and keeps long lived connections open\nsum by (le) (\n  jupyterhub_request_duration_seconds_bucket{\n    app=\"jupyterhub\",\n    namespace=~\"$hub\",\n    handler!=\"jupyterhub.apihandlers.users.SpawnProgressAPIHandler\"\n  }\n  -\n  jupyterhub_request_duration_seconds_bucket{\n    app=\"jupyterhub\",\n    namespace=~\"$hub\",\n    handler!=\"jupyterhub.apihandlers.users.SpawnProgressAPIHandler\"\n  }\n  offset $__rate_interval\n)\n"
    }
   ]
  },
  {
   "title": "Hub response status codes",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n  increase(\n    jupyterhub_request_duration_seconds_count{\n      app=\"jupyterhub\",\n      namespace=~\"$hub\",\n    }[2m]\n  )\n) by (code)\n",
     "legendFormat": "{{ code }}"
    }
   ]
  },
  {
   "title": "All JupyterHub Components CPU",
   "type": "timeseries",
   "description": "The measured unit are CPU cores, and they are written out with SI prefixes, so 100m means 0.1 CPU cores.\n",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "sum(\n  # exclude name=\"\" because the same container can be reported\n# with both no name and `name=k8s_...`,\n# in which case sum() reports double the actual metric\nirate(container_cpu_usage_seconds_total{name!=\"\"}[5m])\n\n  * on (namespace, pod) group_left(container, label_component) \n  group(\n    kube_pod_labels{label_app=\"jupyterhub\", label_component!=\"singleuser-server\", namespace=~\"$hub\"}\n  ) by (label_component, pod, namespace)\n) by (label_component)\n",
     "legendFormat": "{{ label_component }}"
    }
   ]
  },
  {
   "title": "All JupyterHub Components Memory (Working Set)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(\n  # exclude name=\"\" because the same container can be reported\n# with both no name and `name=k8s_...`,\n# in which case sum() reports double the actual metric\ncontainer_memory_working_set_bytes{name!=\"\"}\n\n  * on (namespace, pod) group_left(container, label_component) \n  group(\n    kube_pod_labels{label_app=\"jupyterhub\", label_component!=\"singleuser-server\", namespace=~\"$hub\"}\n  ) by (label_component, pod, namespace)\n) by (label_component)\n",
     "legendFormat": "{{ label_component }}"
    }
   ]
  },
  {
   "title": "Users per node",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 63 },
   "targets": [
    {
     "expr": "sum(\n    # kube_pod_info.node identifies the pod node,\n    # while kube_pod_labels.node is the metrics exporter's node\n    kube_pod_info{node!=\"\", namespace=~\"$hub\"}\n    * on (namespace, pod) group_left() \n  group(\n    kube_pod_labels{label_app=\"jupyterhub\", label_component=\"singleuser-server\", namespace=~\"$hub\"}\n  ) by (label_component, pod, namespace)\n) by (node)\n",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  {
   "title": "Non Running Pods",
   "type": "timeseries",
   "description": "Pods in a non-running state in the hub's namespace.\n\nPods stuck in non-running states often indicate an error condition\n",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 63 },
   "targets": [
    {
     "expr": "sum(\n  kube_pod_status_phase{phase!=\"Running\", namespace=~\"$hub\"}\n) by (phase)\n",
     "legendFormat": "{{phase}}"
    }
   ]
  },
  {
   "title": "Hub DB Disk Space Availability %",
   "type": "timeseries",
   "description": "% of disk space left in the disk storing the JupyterHub sqlite database. If goes to 0, the hub will fail.\n",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "# Free bytes available on the hub db PVC\nsum(kubelet_volume_stats_available_bytes{persistentvolumeclaim=\"hub-db-dir\", namespace=~\"$hub\"}) by (namespace) /\n# Total number of bytes available on the hub db PVC\nsum(kubelet_volume_stats_capacity_bytes{persistentvolumeclaim=\"hub-db-dir\", namespace=~\"$hub\"}) by (namespace)\n",
     "legendFormat": "{{ $hub }}"
    }
   ]
  },
  {
   "title": "Free space (%) in shared volume (Home directories, etc.)",
   "type": "timeseries",
   "description": "% of disk space left in a shared storage volume, typically used for users'\nhome directories.\n\nRequires an additional node_exporter deployment to work. If this graph\nis empty, look at the README for jupyterhub/grafana-dashboards to see\nwhat extra deployment is needed.\n",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "min(\n  node_filesystem_avail_bytes{mountpoint=\"/shared-volume\", component=\"shared-volume-metrics\", namespace=~\"$hub\"}\n  /\n  node_filesystem_size_bytes{mountpoint=\"/shared-volume\", component=\"shared-volume-metrics\", namespace=~\"$hub\"}\n) by (namespace)\n",
     "legendFormat": "{{ namespace }}"
    }
   ]
  },
  { "title": "Anomalous user pods", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 83 } },
  {
   "title": "Very old user pods",
   "type": "table",
   "description": "User pods that have been running for a long time (>8h).\n\nThis often indicates problems with the idle culler\n",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "(\n  time() - (kube_pod_created * on (namespace, pod)  \n  group(\n    kube_pod_labels{label_app=\"jupyterhub\", label_component=\"singleuser-server\", namespace=~\"$hub\"}\n  ) by (label_component, pod, namespace))\n)  > (8 * 60 * 60) # 8 hours is our threshold\n",
     "legendFormat": "{{ namespace }}/{{ pod }}"
    }
   ]
  },
  {
   "title": "User Pods with high CPU usage (>0.5)",
   "type": "table",
   "description": "User pods using a lot of CPU\n\nThis could indicate a runaway process consuming resources\nunnecessarily.\n",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 84 },
   "targets": [
    {
     "expr": "max( # Ideally we just want 'current' value, so max will do\n  irate(container_cpu_usage_seconds_total[5m])\n  * on (namespace, pod) group_left() \n  group(\n    kube_pod_labels{label_app=\"jupyterhub\", label_component=\"singleuser-server\", namespace=~\"$hub\"}\n  ) by (label_component, pod, namespace)\n) by (namespace, pod) > 0.5\n",
     "legendFormat": "{{ namespace }}/{{ pod }}"
    }
   ]
  },
  {
   "title": "User pods with high memory usage (>80% of limit)",
   "type": "table",
   "description": "User pods getting close to their memory limit\n\nOnce they hit their memory limit, user kernels will start dying.\n",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 94 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "max( # Ideally we just want 'current', but max will do. This metric is a gauge, so sum is inappropriate\n  container_memory_working_set_bytes\n  * on (namespace, pod) group_left() \n  group(\n    kube_pod_labels{label_app=\"jupyterhub\", label_component=\"singleuser-server\", namespace=~\"$hub\"}\n  ) by (label_component, pod, namespace)\n) by (namespace, pod)\n/\nsum(\n  kube_pod_container_resource_limits_memory_bytes\n  * on (namespace, pod) group_left() \n  group(\n    kube_pod_labels{label_app=\"jupyterhub\", label_component=\"singleuser-server\", namespace=~\"$hub\"}\n  ) by (label_component, pod, namespace)\n) by (namespace, pod)\n> 0.8\n",
     "legendFormat": "{{ namespace }}/{{ pod }}"
    }
   ]
  }
 ]
}