{
 "title": "NFS usage, NFS server, and Prometheus server diagnostics",
 "tags": [
  "kubernetes",
  "nfs",
  "jupyterhub-home-nfs",
  "prometheus"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "cluster", "label": "cluster" },
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   { "name": "show_requests", "label": "CPU/Memory requests", "query": "Show : 1,Hide : 0" },
   { "name": "show_limits", "label": "CPU/Memory limits", "query": "Show : 1,Hide : 0" },
   { "name": "show_capacity", "label": "Storage capacity", "query": "Show : 1,Hide : 0" }
  ]
 },
 "panels": [
  { "title": "NFS usage diagnostics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "NFS requests, per node",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(irate(node_nfs_requests_total[5m])) by (node) > 0\n",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  {
   "title": "NFS requests, per operation",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum(irate(node_nfs_requests_total[5m])) by (method) > 0\n",
     "legendFormat": "{{ method }}"
    }
   ]
  },
  { "title": "NFS server diagnostics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "NFS server CPU usage",
   "type": "timeseries",
   "description": "The measured unit are CPU cores, and they are written out with SI prefixes, so 100m means 0.1 CPU cores.\n",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{pod=~\".*home-nfs.*\", container!=\"\"}[5m])) by (namespace, container)\n",
     "legendFormat": "{{namespace}}: {{container}}"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{pod=~\".*home-nfs-.*\", container!=\"\", resource=\"cpu\"}) by (namespace, container)\nand on() vector($show_requests) == 1\n",
     "legendFormat": "request ({{namespace}}: {{container}})"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{pod=~\".*home-nfs-.*\", container!=\"\", resource=\"cpu\"}) by (namespace, container)\nand on() vector($show_limits) == 1\n",
     "legendFormat": "limit ({{namespace}}: {{container}})"
    }
   ]
  },
  {
   "title": "NFS server memory usage (working set)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{pod=~\".*home-nfs-.*\", container!=\"\"}) by (namespace, container)\n",
     "legendFormat": "{{namespace}}: {{container}}"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{pod=~\".*home-nfs-.*\", container!=\"\", resource=\"memory\"}) by (namespace, container)\nand on() vector($show_requests) == 1\n",
     "legendFormat": "request ({{namespace}}: {{container}})"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{pod=~\".*home-nfs-.*\", container!=\"\", resource=\"memory\"}) by (namespace, container)\nand on() vector($show_limits) == 1\n",
     "legendFormat": "limit ({{namespace}}: {{container}})"
    }
   ]
  },
  {
   "title": "NFS server used disk space",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(kubelet_volume_stats_used_bytes{persistentvolumeclaim=~\".*home-nfs\"}) by (namespace, persistentvolumeclaim)\n",
     "legendFormat": "{{namespace}}: {{persistentvolumeclaim}}"
    },
    {
     "expr": "sum(kubelet_volume_stats_capacity_bytes{persistentvolumeclaim=~\".*home-nfs\"}) by (namespace, persistentvolumeclaim)\nand on() vector($show_capacity) == 1\n",
     "legendFormat": "capacity ({{namespace}}: {{persistentvolumeclaim}})"
    }
   ]
  },
  {
   "title": "NFS server network usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(irate(container_network_receive_bytes_total{pod=~\".*-home-nfs-.*\"}[5m])) by (namespace)\n",
     "legendFormat": "receive ({{namespace}})"
    },
    {
     "expr": "sum(irate(container_network_transmit_bytes_total{pod=~\".*-home-nfs-.*\"}[5m])) by (namespace)\n",
     "legendFormat": "transmit ({{namespace}})"
    }
   ]
  },
  { "title": "Prometheus server diagnostics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Prometheus server CPU usage",
   "type": "timeseries",
   "description": "The measured unit are CPU cores, and they are written out with SI prefixes, so 100m means 0.1 CPU cores.\n",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{pod=~\".*prometheus-server-.*\", container!=\"\"}[5m])) by (namespace, container)\n",
     "legendFormat": "{{namespace}}: {{container}}"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{pod=~\".*prometheus-server-.*\", container!=\"\", resource=\"cpu\"}) by (namespace, container)\nand on() vector($show_requests) == 1\n",
     "legendFormat": "request ({{namespace}}: {{container}})"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{pod=~\".*prometheus-server-.*\", container!=\"\", resource=\"cpu\"}) by (namespace, container)\nand on() vector($show_limits) == 1\n",
     "legendFormat": "limit ({{namespace}}: {{container}})"
    }
   ]
  },
  {
   "title": "Prometheus server memory usage (working set)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{pod=~\".*prometheus-server-.*\", container!=\"\"}) by (namespace, container)\n",
     "legendFormat": "{{namespace}}: {{container}}"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{pod=~\".*prometheus-server-.*\", container!=\"\", resource=\"memory\"}) by (namespace, container)\nand on() vector($show_requests) == 1\n",
     "legendFormat": "request ({{namespace}}: {{container}})"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{pod=~\".*prometheus-server-.*\", container!=\"\", resource=\"memory\"}) by (namespace, container)\nand on() vector($show_limits) == 1\n",
     "legendFormat": "limit ({{namespace}}: {{container}})"
    }
   ]
  },
  {
   "title": "Prometheus server used disk space",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(kubelet_volume_stats_used_bytes{persistentvolumeclaim=~\".*-prometheus-server\"}) by (namespace, persistentvolumeclaim)\n",
     "legendFormat": "{{namespace}}: {{persistentvolumeclaim}}"
    },
    {
     "expr": "sum(kubelet_volume_stats_capacity_bytes{persistentvolumeclaim=~\".*-prometheus-server\"}) by (namespace, persistentvolumeclaim)\nand on() vector($show_capacity) == 1\n",
     "legendFormat": "capacity ({{namespace}}: {{persistentvolumeclaim}})"
    }
   ]
  },
  {
   "title": "Prometheus server network usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(irate(container_network_receive_bytes_total{pod=~\".*-prometheus-server-.*\"}[5m])) by (namespace)\n",
     "legendFormat": "receive ({{namespace}})"
    },
    {
     "expr": "sum(irate(container_network_transmit_bytes_total{pod=~\".*-prometheus-server-.*\"}[5m])) by (namespace)\n",
     "legendFormat": "transmit ({{namespace}})"
    }
   ]
  }
 ]
}